### PR TITLE
support for resuming upload

### PR DESCRIPTION
**Pull request by johnbradley**
Tries to fetch project before creating a new one so we can resume uploads.

### CODE REVIEW

**Review by dleehr — COMMENTED** [review]
I see that `NothingToUploadException` is no longer raised or caught. Obviously when resuming an upload, it's possible that there is actually nothing left to _finish_, but I'm curious if we're losing anything by removing this logic (or if it needs to be re-added later)

**Comment by johnbradley** [comment]
> I'm curious if we're losing anything by removing this logic (or if it needs to be re-added later)

I'm not sure what we would be losing. After the project is uploaded the project is shared with specified users. If sharing fails and we retry the job it seems like we would want it to try to share again instead of giving up. If the concern is accidentally sharing multiple times we could add a check to see if the user already has the expected permissions.

**Comment by dleehr** [comment]
I meant that the original behavior was to raise an exception if there’s nothing to upload. Looks like that’s gone now, but maybe I’m missing something.

**Comment by johnbradley** [comment]
>  I meant that the original behavior was to raise an exception if there’s nothing to upload. Looks like that’s gone now, but maybe I’m missing something.

This logic was intentionally removed. Previously we always created a new project so having nothing to upload would be unexpected. With this change we don't always create a new project so having nothing to upload is a possibility when the project already exists. I could add the check back in if we create a new project. 

After thinking about this a little bit more I think even with a new project you would never have `NothingToUpload`. Even if you pass an empty directory (the scenario I was thinking about when I originally wrote this check) to upload it would need to upload the directory.

**Comment by dleehr** [comment]
> This logic was intentionally removed.

👍

**Review by dleehr — APPROVED** [review]

**Pull request merged**
